from flask import Flask, render_template, request, jsonify, send_file
import os
import requests
import uuid

from google import genai
from transformers import pipeline

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

app = Flask(__name__)

# =========================
# GEMINI CONFIG
# =========================

client = genai.Client(
    api_key="AIzaSyDKI_G_zeY5R-OMkw2yAdU0i8-VMIYaEuU"
)

MODEL = "models/gemini-2.5-flash"

# =========================
# AI FOOD MODEL
# =========================

classifier = pipeline(
    "image-classification",
    model="nateraw/food"
)

# =========================
# HOME
# =========================

@app.route('/')
def home():
    return render_template('index.html')

# =========================
# RESULT PAGE
# =========================

@app.route('/result', methods=['POST'])
def result():

    try:
        name = request.form.get('name')
        gender = request.form.get('gender')
        age = request.form.get('age')
        height = float(request.form.get('height'))
        weight = float(request.form.get('weight'))
        goal = request.form.get('goal')
        allergy = request.form.get('allergy')

        # BMI
        bmi = weight / (height ** 2)

        if bmi < 18.5:
            category = "Underweight"
            suggestion = "You should gain weight 💪"
        elif bmi < 25:
            category = "Normal"
            suggestion = "Maintain your health 👍"
        else:
            category = "Overweight"
            suggestion = "You should lose weight 🏃"

        # IMAGE
        image = request.files['food_image']

        upload_folder = os.path.join(os.getcwd(), "uploads")
        os.makedirs(upload_folder, exist_ok=True)

        unique_name = str(uuid.uuid4()) + "_" + image.filename
        filepath = os.path.join(upload_folder, unique_name)
        image.save(filepath)

        # FOOD DETECTION
        try:
            ai_result = classifier(filepath)
            food = ai_result[0]['label']
            confidence = round(ai_result[0]['score'] * 100, 2)
        except:
            food = "Food"
            confidence = 0

        # CALORIES API
        cal_api_key = "RzWiBf5e4HYdn1pP/semXg==QBP99Idram2UvGSX"
        url = f"https://api.calorieninjas.com/v1/nutrition?query={food}"

        calories = "Not Found"

        try:
            response = requests.get(url, headers={'X-Api-Key': cal_api_key})
            data = response.json()

            if data.get('items'):
                calories = data['items'][0]['calories']
        except:
            calories = "Error"

        return render_template(
            "result.html",
            name=name,
            gender=gender,
            age=age,
            bmi=round(bmi, 2),
            category=category,
            suggestion=suggestion,
            goal=goal,
            allergy=allergy,
            food_name=food,
            calories=calories,
            confidence=confidence
        )

    except Exception as e:
        return f"ERROR: {str(e)}"

# =========================
# PDF DOWNLOAD ROUTE (FIXED)
# =========================

@app.route('/download-report')
def download_report():

    pdf_path = "health_report.pdf"

    doc = SimpleDocTemplate(pdf_path)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("AI Smart Health Report", styles['Title']))
    elements.append(Spacer(1, 20))

    # DATA
    fields = [
        ("Name", request.args.get('name')),
        ("Gender", request.args.get('gender')),
        ("Age", request.args.get('age')),
        ("BMI", request.args.get('bmi')),
        ("Category", request.args.get('category')),
        ("Suggestion", request.args.get('suggestion')),
        ("Food", request.args.get('food')),
        ("Calories", request.args.get('calories')),
    ]

    for label, value in fields:
        elements.append(Paragraph(f"<b>{label}:</b> {value}", styles['BodyText']))
        elements.append(Spacer(1, 10))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Generated by AI Smart Health Assistant", styles['Italic']))

    doc.build(elements)

    return send_file(pdf_path, as_attachment=True)

# =========================
# CHATBOT
# =========================

@app.route('/ask', methods=['POST'])
def ask():

    try:
        message = request.form['message']

        response = client.models.generate_content(
            model=MODEL,
            contents=message
        )

        return jsonify({"reply": response.text})

    except Exception as e:
        return jsonify({"reply": str(e)})

# =========================
# RUN
# =========================

if __name__ == '__main__':
    app.run(host="0.0.0.0", port=5000)